### Register user
POST http://localhost:8000/auth/sign-up
Content-Type: application/json

{
  "name": "Nikolai",
  "email": "nikolai@example.com",
  "password": "$pass123"
}

### Getting user token
POST http://localhost:8000/auth/sign-in
Content-Type: application/json

{
  "email": "nikolai@example.com",
  "password": "$pass123"
}

### Log out
POST http://localhost:8000/auth/sign-out
Content-Type: application/json

{
  "token": ""
}

### Get all notes
GET http://localhost:8000/notes/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpc3MiOiIyMDIzLTAzLTIzIDE1OjU0OjM0LjE2MDk2MyJ9.C6iWceOiUBlGJ5y5QSFcp_RXSuI2F7UZgFpTRKqtteE

### Get note by id
GET http://localhost:8000/notes/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpc3MiOiIyMDIzLTAzLTIzIDE1OjU0OjM0LjE2MDk2MyJ9.C6iWceOiUBlGJ5y5QSFcp_RXSuI2F7UZgFpTRKqtteE

### Create note
POST http://localhost:8000/notes/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpc3MiOiIyMDIzLTAzLTIzIDE1OjU0OjM0LjE2MDk2MyJ9.C6iWceOiUBlGJ5y5QSFcp_RXSuI2F7UZgFpTRKqtteE

{
  "title": "My room",
  "text": "12142"
}

### Edit note
PUT http://localhost:8000/notes/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpc3MiOiIyMDIzLTAzLTIzIDE1OjU0OjM0LjE2MDk2MyJ9.C6iWceOiUBlGJ5y5QSFcp_RXSuI2F7UZgFpTRKqtteE

{
  "title": "My room",
  "text": "12141"
}

### Delete note
DELETE http://localhost:8000/notes/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpc3MiOiIyMDIzLTAzLTIzIDE1OjU0OjM0LjE2MDk2MyJ9.C6iWceOiUBlGJ5y5QSFcp_RXSuI2F7UZgFpTRKqtteE
